# Generated by Django 5.0.2 on 2025-06-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
    ]
