# Generated by Django 5.0.2 on 2025-06-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='expires_at',
        ),
    ]
