# Generated by Django 5.0.2 on 2025-06-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_question_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_wassce_related',
            field=models.BooleanField(default=False),
        ),
    ]
