# Generated by Django 5.0.2 on 2025-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_is_wassce_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_wassce_related',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_wassce_related',
            field=models.BooleanField(default=False),
        ),
    ]
