# Generated by Django 5.0.2 on 2025-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_question_is_wassce_related_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_wassce_related',
            field=models.BooleanField(default=True),
        ),
    ]
