# Generated by Django 5.0.2 on 2025-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quiz_is_wassce_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
