# Generated by Django 5.0.2 on 2025-06-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_topics',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of selected subjects and their topics'),
        ),
    ]
