# Generated by Django 5.0.2 on 2025-06-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_selected_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exam_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
